package com.therealdanvega.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CcCoR4tData generated by hbm2java
 */
@Entity
@Table(name = "_cc_co_r4t_data", catalog = "testts")
public class CcCoR4tData implements java.io.Serializable {

	private int courseContentId;
	private Integer total;
	private Integer coi1;
	private Integer coi2;
	private Integer coi30;
	private Integer coi39;
	private Integer coi40;

	public CcCoR4tData() {
	}

	public CcCoR4tData(int courseContentId) {
		this.courseContentId = courseContentId;
	}

	public CcCoR4tData(int courseContentId, Integer total, Integer coi1, Integer coi2, Integer coi30, Integer coi39,
			Integer coi40) {
		this.courseContentId = courseContentId;
		this.total = total;
		this.coi1 = coi1;
		this.coi2 = coi2;
		this.coi30 = coi30;
		this.coi39 = coi39;
		this.coi40 = coi40;
	}

	@Id

	@Column(name = "course_content_id", unique = true, nullable = false)
	public int getCourseContentId() {
		return this.courseContentId;
	}

	public void setCourseContentId(int courseContentId) {
		this.courseContentId = courseContentId;
	}

	@Column(name = "total")
	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	@Column(name = "coi_1")
	public Integer getCoi1() {
		return this.coi1;
	}

	public void setCoi1(Integer coi1) {
		this.coi1 = coi1;
	}

	@Column(name = "coi_2")
	public Integer getCoi2() {
		return this.coi2;
	}

	public void setCoi2(Integer coi2) {
		this.coi2 = coi2;
	}

	@Column(name = "coi_30")
	public Integer getCoi30() {
		return this.coi30;
	}

	public void setCoi30(Integer coi30) {
		this.coi30 = coi30;
	}

	@Column(name = "coi_39")
	public Integer getCoi39() {
		return this.coi39;
	}

	public void setCoi39(Integer coi39) {
		this.coi39 = coi39;
	}

	@Column(name = "coi_40")
	public Integer getCoi40() {
		return this.coi40;
	}

	public void setCoi40(Integer coi40) {
		this.coi40 = coi40;
	}

}
