package com.therealdanvega.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CourseContent generated by hbm2java
 */
@Entity
@Table(name = "course_content", catalog = "testts")
public class CourseContent implements java.io.Serializable {

	private Integer courseContentId;
	private Course course;
	private CourseContent courseContent;
	private String courseContentCode;
	private String courseContentName;
	private String courseContentDesc;
	private Integer courseContentPercentage;
	private Integer courseContentOrder;
	private Set<QgroupContentMap> qgroupContentMaps = new HashSet<QgroupContentMap>(0);
	private Set<CourseContent> courseContents = new HashSet<CourseContent>(0);
	private Set<CcoMap> ccoMaps = new HashSet<CcoMap>(0);
	private Set<ContentComment> contentComments = new HashSet<ContentComment>(0);
	private Set<QuestionContentMap> questionContentMaps = new HashSet<QuestionContentMap>(0);

	public CourseContent() {
	}

	public CourseContent(String courseContentDesc) {
		this.courseContentDesc = courseContentDesc;
	}

	public CourseContent(Course course, CourseContent courseContent, String courseContentCode, String courseContentName,
			String courseContentDesc, Integer courseContentPercentage, Integer courseContentOrder,
			Set<QgroupContentMap> qgroupContentMaps, Set<CourseContent> courseContents, Set<CcoMap> ccoMaps,
			Set<ContentComment> contentComments, Set<QuestionContentMap> questionContentMaps) {
		this.course = course;
		this.courseContent = courseContent;
		this.courseContentCode = courseContentCode;
		this.courseContentName = courseContentName;
		this.courseContentDesc = courseContentDesc;
		this.courseContentPercentage = courseContentPercentage;
		this.courseContentOrder = courseContentOrder;
		this.qgroupContentMaps = qgroupContentMaps;
		this.courseContents = courseContents;
		this.ccoMaps = ccoMaps;
		this.contentComments = contentComments;
		this.questionContentMaps = questionContentMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "course_content_id", unique = true, nullable = false)
	public Integer getCourseContentId() {
		return this.courseContentId;
	}

	public void setCourseContentId(Integer courseContentId) {
		this.courseContentId = courseContentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id")
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_parentcontent_id")
	public CourseContent getCourseContent() {
		return this.courseContent;
	}

	public void setCourseContent(CourseContent courseContent) {
		this.courseContent = courseContent;
	}

	@Column(name = "course_content_code", length = 10)
	public String getCourseContentCode() {
		return this.courseContentCode;
	}

	public void setCourseContentCode(String courseContentCode) {
		this.courseContentCode = courseContentCode;
	}

	@Column(name = "course_content_name", length = 200)
	public String getCourseContentName() {
		return this.courseContentName;
	}

	public void setCourseContentName(String courseContentName) {
		this.courseContentName = courseContentName;
	}

	@Column(name = "course_content_desc", nullable = false, length = 65535)
	public String getCourseContentDesc() {
		return this.courseContentDesc;
	}

	public void setCourseContentDesc(String courseContentDesc) {
		this.courseContentDesc = courseContentDesc;
	}

	@Column(name = "course_content_percentage", precision = 8, scale = 0)
	public Integer getCourseContentPercentage() {
		return this.courseContentPercentage;
	}

	public void setCourseContentPercentage(Integer courseContentPercentage) {
		this.courseContentPercentage = courseContentPercentage;
	}

	@Column(name = "course_content_order")
	public Integer getCourseContentOrder() {
		return this.courseContentOrder;
	}

	public void setCourseContentOrder(Integer courseContentOrder) {
		this.courseContentOrder = courseContentOrder;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseContent")
	public Set<QgroupContentMap> getQgroupContentMaps() {
		return this.qgroupContentMaps;
	}

	public void setQgroupContentMaps(Set<QgroupContentMap> qgroupContentMaps) {
		this.qgroupContentMaps = qgroupContentMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseContent")
	public Set<CourseContent> getCourseContents() {
		return this.courseContents;
	}

	public void setCourseContents(Set<CourseContent> courseContents) {
		this.courseContents = courseContents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseContent")
	public Set<CcoMap> getCcoMaps() {
		return this.ccoMaps;
	}

	public void setCcoMaps(Set<CcoMap> ccoMaps) {
		this.ccoMaps = ccoMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseContent")
	public Set<ContentComment> getContentComments() {
		return this.contentComments;
	}

	public void setContentComments(Set<ContentComment> contentComments) {
		this.contentComments = contentComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseContent")
	public Set<QuestionContentMap> getQuestionContentMaps() {
		return this.questionContentMaps;
	}

	public void setQuestionContentMaps(Set<QuestionContentMap> questionContentMaps) {
		this.questionContentMaps = questionContentMaps;
	}

}
