package com.therealdanvega.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CourseRequiredLevel generated by hbm2java
 */
@Entity
@Table(name = "course_required_level", catalog = "testts")
public class CourseRequiredLevel implements java.io.Serializable {

	private Integer courseRequiredLevelId;
	private String courseRequiredLevelCode;
	private String courseRequiredLevelDesc;
	private Set<ProgramCourseMap> programCourseMaps = new HashSet<ProgramCourseMap>(0);

	public CourseRequiredLevel() {
	}

	public CourseRequiredLevel(String courseRequiredLevelCode, String courseRequiredLevelDesc) {
		this.courseRequiredLevelCode = courseRequiredLevelCode;
		this.courseRequiredLevelDesc = courseRequiredLevelDesc;
	}

	public CourseRequiredLevel(String courseRequiredLevelCode, String courseRequiredLevelDesc,
			Set<ProgramCourseMap> programCourseMaps) {
		this.courseRequiredLevelCode = courseRequiredLevelCode;
		this.courseRequiredLevelDesc = courseRequiredLevelDesc;
		this.programCourseMaps = programCourseMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "course_required_level_id", unique = true, nullable = false)
	public Integer getCourseRequiredLevelId() {
		return this.courseRequiredLevelId;
	}

	public void setCourseRequiredLevelId(Integer courseRequiredLevelId) {
		this.courseRequiredLevelId = courseRequiredLevelId;
	}

	@Column(name = "course_required_level_code", nullable = false, length = 100)
	public String getCourseRequiredLevelCode() {
		return this.courseRequiredLevelCode;
	}

	public void setCourseRequiredLevelCode(String courseRequiredLevelCode) {
		this.courseRequiredLevelCode = courseRequiredLevelCode;
	}

	@Column(name = "course_required_level_desc", nullable = false, length = 65535)
	public String getCourseRequiredLevelDesc() {
		return this.courseRequiredLevelDesc;
	}

	public void setCourseRequiredLevelDesc(String courseRequiredLevelDesc) {
		this.courseRequiredLevelDesc = courseRequiredLevelDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseRequiredLevel")
	public Set<ProgramCourseMap> getProgramCourseMaps() {
		return this.programCourseMaps;
	}

	public void setProgramCourseMaps(Set<ProgramCourseMap> programCourseMaps) {
		this.programCourseMaps = programCourseMaps;
	}

}
