package com.therealdanvega.domain;
// Generated Mar 4, 2018 2:56:35 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CourseReviewerDecision generated by hbm2java
 */
@Entity
@Table(name = "course_reviewer_decision", catalog = "mycontact")
public class CourseReviewerDecision implements java.io.Serializable {

	private Integer courseReviewerDecisionId;
	private String courseReviewerDecisionCode;
	private String courseReviewerDecisionDesc;
	private Set<ContentComment> contentComments = new HashSet<ContentComment>(0);
	private Set<ContentComment> contentComments_1 = new HashSet<ContentComment>(0);
	private Set<CourseComment> courseComments = new HashSet<CourseComment>(0);
	private Set<CourseComment> courseComments_1 = new HashSet<CourseComment>(0);

	public CourseReviewerDecision() {
	}

	public CourseReviewerDecision(String courseReviewerDecisionCode, String courseReviewerDecisionDesc) {
		this.courseReviewerDecisionCode = courseReviewerDecisionCode;
		this.courseReviewerDecisionDesc = courseReviewerDecisionDesc;
	}

	public CourseReviewerDecision(String courseReviewerDecisionCode, String courseReviewerDecisionDesc,
			Set<ContentComment> contentComments, Set<ContentComment> contentComments_1,
			Set<CourseComment> courseComments, Set<CourseComment> courseComments_1) {
		this.courseReviewerDecisionCode = courseReviewerDecisionCode;
		this.courseReviewerDecisionDesc = courseReviewerDecisionDesc;
		this.contentComments = contentComments;
		this.contentComments_1 = contentComments_1;
		this.courseComments = courseComments;
		this.courseComments_1 = courseComments_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "course_reviewer_decision_id", unique = true, nullable = false)
	public Integer getCourseReviewerDecisionId() {
		return this.courseReviewerDecisionId;
	}

	public void setCourseReviewerDecisionId(Integer courseReviewerDecisionId) {
		this.courseReviewerDecisionId = courseReviewerDecisionId;
	}

	@Column(name = "course_reviewer_decision_code", nullable = false, length = 100)
	public String getCourseReviewerDecisionCode() {
		return this.courseReviewerDecisionCode;
	}

	public void setCourseReviewerDecisionCode(String courseReviewerDecisionCode) {
		this.courseReviewerDecisionCode = courseReviewerDecisionCode;
	}

	@Column(name = "course_reviewer_decision_desc", nullable = false, length = 65535)
	public String getCourseReviewerDecisionDesc() {
		return this.courseReviewerDecisionDesc;
	}

	public void setCourseReviewerDecisionDesc(String courseReviewerDecisionDesc) {
		this.courseReviewerDecisionDesc = courseReviewerDecisionDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseReviewerDecision")
	public Set<ContentComment> getContentComments() {
		return this.contentComments;
	}

	public void setContentComments(Set<ContentComment> contentComments) {
		this.contentComments = contentComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseReviewerDecision")
	public Set<ContentComment> getContentComments_1() {
		return this.contentComments_1;
	}

	public void setContentComments_1(Set<ContentComment> contentComments_1) {
		this.contentComments_1 = contentComments_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseReviewerDecision")
	public Set<CourseComment> getCourseComments() {
		return this.courseComments;
	}

	public void setCourseComments(Set<CourseComment> courseComments) {
		this.courseComments = courseComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseReviewerDecision")
	public Set<CourseComment> getCourseComments_1() {
		return this.courseComments_1;
	}

	public void setCourseComments_1(Set<CourseComment> courseComments_1) {
		this.courseComments_1 = courseComments_1;
	}

}
