package com.therealdanvega.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EducationalProgram generated by hbm2java
 */
@Entity
@Table(name = "educational_program", catalog = "testts")
public class EducationalProgram implements java.io.Serializable {

	private Integer eduProgramId;
	private Faculty faculty;
	private String eduProgramCode;
	private String eduProgramNameVn;
	private String eduProgramNameEn;
	private String eduProgramNameShort;
	private Date eduProgramStartYear;
	private Date eduProgramEndYear;
	private String eduProgramDesc;
	private String eduProgramLink;
	private Set<ProgramAccessMode> programAccessModes = new HashSet<ProgramAccessMode>(0);
	private Set<StudentOutcome> studentOutcomes = new HashSet<StudentOutcome>(0);
	private Set<Peo> peos = new HashSet<Peo>(0);
	private Set<ProgramCourseMap> programCourseMaps = new HashSet<ProgramCourseMap>(0);

	public EducationalProgram() {
	}

	public EducationalProgram(String eduProgramCode, String eduProgramNameVn, String eduProgramNameEn,
			Date eduProgramStartYear) {
		this.eduProgramCode = eduProgramCode;
		this.eduProgramNameVn = eduProgramNameVn;
		this.eduProgramNameEn = eduProgramNameEn;
		this.eduProgramStartYear = eduProgramStartYear;
	}

	public EducationalProgram(Faculty faculty, String eduProgramCode, String eduProgramNameVn, String eduProgramNameEn,
			String eduProgramNameShort, Date eduProgramStartYear, Date eduProgramEndYear, String eduProgramDesc,
			String eduProgramLink, Set<ProgramAccessMode> programAccessModes, Set<StudentOutcome> studentOutcomes,
			Set<Peo> peos, Set<ProgramCourseMap> programCourseMaps) {
		this.faculty = faculty;
		this.eduProgramCode = eduProgramCode;
		this.eduProgramNameVn = eduProgramNameVn;
		this.eduProgramNameEn = eduProgramNameEn;
		this.eduProgramNameShort = eduProgramNameShort;
		this.eduProgramStartYear = eduProgramStartYear;
		this.eduProgramEndYear = eduProgramEndYear;
		this.eduProgramDesc = eduProgramDesc;
		this.eduProgramLink = eduProgramLink;
		this.programAccessModes = programAccessModes;
		this.studentOutcomes = studentOutcomes;
		this.peos = peos;
		this.programCourseMaps = programCourseMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "edu_program_id", unique = true, nullable = false)
	public Integer getEduProgramId() {
		return this.eduProgramId;
	}

	public void setEduProgramId(Integer eduProgramId) {
		this.eduProgramId = eduProgramId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "faculty_id")
	public Faculty getFaculty() {
		return this.faculty;
	}

	public void setFaculty(Faculty faculty) {
		this.faculty = faculty;
	}

	@Column(name = "edu_program_code", nullable = false, length = 20)
	public String getEduProgramCode() {
		return this.eduProgramCode;
	}

	public void setEduProgramCode(String eduProgramCode) {
		this.eduProgramCode = eduProgramCode;
	}

	@Column(name = "edu_program_name_vn", nullable = false, length = 65535)
	public String getEduProgramNameVn() {
		return this.eduProgramNameVn;
	}

	public void setEduProgramNameVn(String eduProgramNameVn) {
		this.eduProgramNameVn = eduProgramNameVn;
	}

	@Column(name = "edu_program_name_en", nullable = false, length = 65535)
	public String getEduProgramNameEn() {
		return this.eduProgramNameEn;
	}

	public void setEduProgramNameEn(String eduProgramNameEn) {
		this.eduProgramNameEn = eduProgramNameEn;
	}

	@Column(name = "edu_program_name_short", length = 20)
	public String getEduProgramNameShort() {
		return this.eduProgramNameShort;
	}

	public void setEduProgramNameShort(String eduProgramNameShort) {
		this.eduProgramNameShort = eduProgramNameShort;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "edu_program_start_year", nullable = false, length = 10)
	public Date getEduProgramStartYear() {
		return this.eduProgramStartYear;
	}

	public void setEduProgramStartYear(Date eduProgramStartYear) {
		this.eduProgramStartYear = eduProgramStartYear;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "edu_program_end_year", length = 10)
	public Date getEduProgramEndYear() {
		return this.eduProgramEndYear;
	}

	public void setEduProgramEndYear(Date eduProgramEndYear) {
		this.eduProgramEndYear = eduProgramEndYear;
	}

	@Column(name = "edu_program_desc", length = 65535)
	public String getEduProgramDesc() {
		return this.eduProgramDesc;
	}

	public void setEduProgramDesc(String eduProgramDesc) {
		this.eduProgramDesc = eduProgramDesc;
	}

	@Column(name = "edu_program_link", length = 65535)
	public String getEduProgramLink() {
		return this.eduProgramLink;
	}

	public void setEduProgramLink(String eduProgramLink) {
		this.eduProgramLink = eduProgramLink;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "educationalProgram")
	public Set<ProgramAccessMode> getProgramAccessModes() {
		return this.programAccessModes;
	}

	public void setProgramAccessModes(Set<ProgramAccessMode> programAccessModes) {
		this.programAccessModes = programAccessModes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "educationalProgram")
	public Set<StudentOutcome> getStudentOutcomes() {
		return this.studentOutcomes;
	}

	public void setStudentOutcomes(Set<StudentOutcome> studentOutcomes) {
		this.studentOutcomes = studentOutcomes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "educationalProgram")
	public Set<Peo> getPeos() {
		return this.peos;
	}

	public void setPeos(Set<Peo> peos) {
		this.peos = peos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "educationalProgram")
	public Set<ProgramCourseMap> getProgramCourseMaps() {
		return this.programCourseMaps;
	}

	public void setProgramCourseMaps(Set<ProgramCourseMap> programCourseMaps) {
		this.programCourseMaps = programCourseMaps;
	}

}
