package com.therealdanvega.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Genquestest generated by hbm2java
 */
@Entity
@Table(name = "_genquestest", catalog = "testts")
public class Genquestest implements java.io.Serializable {

	private int questionId;
	private Integer coiId;

	public Genquestest() {
	}

	public Genquestest(int questionId) {
		this.questionId = questionId;
	}

	public Genquestest(int questionId, Integer coiId) {
		this.questionId = questionId;
		this.coiId = coiId;
	}

	@Id

	@Column(name = "question_id", unique = true, nullable = false)
	public int getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

	@Column(name = "coi_id")
	public Integer getCoiId() {
		return this.coiId;
	}

	public void setCoiId(Integer coiId) {
		this.coiId = coiId;
	}

}
