package com.therealdanvega.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PeoSoMap generated by hbm2java
 */
@Entity
@Table(name = "peo_so_map", catalog = "testts")
public class PeoSoMap implements java.io.Serializable {

	private Integer psmId;
	private Peo peo;
	private StudentOutcome studentOutcome;
	private int psmCode;
	private Date psmDate;
	private boolean psmIsused;
	private Set<PeoiSoiMap> peoiSoiMaps = new HashSet<PeoiSoiMap>(0);

	public PeoSoMap() {
	}

	public PeoSoMap(int psmCode, boolean psmIsused) {
		this.psmCode = psmCode;
		this.psmIsused = psmIsused;
	}

	public PeoSoMap(Peo peo, StudentOutcome studentOutcome, int psmCode, Date psmDate, boolean psmIsused,
			Set<PeoiSoiMap> peoiSoiMaps) {
		this.peo = peo;
		this.studentOutcome = studentOutcome;
		this.psmCode = psmCode;
		this.psmDate = psmDate;
		this.psmIsused = psmIsused;
		this.peoiSoiMaps = peoiSoiMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "psm_id", unique = true, nullable = false)
	public Integer getPsmId() {
		return this.psmId;
	}

	public void setPsmId(Integer psmId) {
		this.psmId = psmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "peo_id")
	public Peo getPeo() {
		return this.peo;
	}

	public void setPeo(Peo peo) {
		this.peo = peo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sov_id")
	public StudentOutcome getStudentOutcome() {
		return this.studentOutcome;
	}

	public void setStudentOutcome(StudentOutcome studentOutcome) {
		this.studentOutcome = studentOutcome;
	}

	@Column(name = "psm_code", nullable = false)
	public int getPsmCode() {
		return this.psmCode;
	}

	public void setPsmCode(int psmCode) {
		this.psmCode = psmCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "psm_date", length = 10)
	public Date getPsmDate() {
		return this.psmDate;
	}

	public void setPsmDate(Date psmDate) {
		this.psmDate = psmDate;
	}

	@Column(name = "psm_isused", nullable = false)
	public boolean isPsmIsused() {
		return this.psmIsused;
	}

	public void setPsmIsused(boolean psmIsused) {
		this.psmIsused = psmIsused;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "peoSoMap")
	public Set<PeoiSoiMap> getPeoiSoiMaps() {
		return this.peoiSoiMaps;
	}

	public void setPeoiSoiMaps(Set<PeoiSoiMap> peoiSoiMaps) {
		this.peoiSoiMaps = peoiSoiMaps;
	}

}
