package com.therealdanvega.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QsolutionComponent generated by hbm2java
 */
@Entity
@Table(name = "qsolution_component", catalog = "testts")
public class QsolutionComponent implements java.io.Serializable {

	private Integer qsolutionComponentId;
	private FillableElement fillableElement;
	private Qsolution qsolution;
	private QuestionItem questionItemByNextItemId;
	private QuestionItem questionItemByCurrItemId;

	public QsolutionComponent() {
	}

	public QsolutionComponent(FillableElement fillableElement, Qsolution qsolution,
			QuestionItem questionItemByNextItemId, QuestionItem questionItemByCurrItemId) {
		this.fillableElement = fillableElement;
		this.qsolution = qsolution;
		this.questionItemByNextItemId = questionItemByNextItemId;
		this.questionItemByCurrItemId = questionItemByCurrItemId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "qsolution_component_id", unique = true, nullable = false)
	public Integer getQsolutionComponentId() {
		return this.qsolutionComponentId;
	}

	public void setQsolutionComponentId(Integer qsolutionComponentId) {
		this.qsolutionComponentId = qsolutionComponentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fill_element_id")
	public FillableElement getFillableElement() {
		return this.fillableElement;
	}

	public void setFillableElement(FillableElement fillableElement) {
		this.fillableElement = fillableElement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "qsolution_id")
	public Qsolution getQsolution() {
		return this.qsolution;
	}

	public void setQsolution(Qsolution qsolution) {
		this.qsolution = qsolution;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "next_item_id")
	public QuestionItem getQuestionItemByNextItemId() {
		return this.questionItemByNextItemId;
	}

	public void setQuestionItemByNextItemId(QuestionItem questionItemByNextItemId) {
		this.questionItemByNextItemId = questionItemByNextItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "curr_item_id")
	public QuestionItem getQuestionItemByCurrItemId() {
		return this.questionItemByCurrItemId;
	}

	public void setQuestionItemByCurrItemId(QuestionItem questionItemByCurrItemId) {
		this.questionItemByCurrItemId = questionItemByCurrItemId;
	}

}
