package com.therealdanvega.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QuestionItem generated by hbm2java
 */
@Entity
@Table(name = "question_item", catalog = "testts")
public class QuestionItem implements java.io.Serializable {

	private Integer itemId;
	private Question question;
	private String itemCode;
	private String itemDesc;
	private Byte itemOrder;
	private String itemReviewerComment;
	private String itemTakerComment;
	private Set<QuestionItemInfo> questionItemInfos = new HashSet<QuestionItemInfo>(0);
	private Set<FillableElement> fillableElements = new HashSet<FillableElement>(0);
	private Set<TakersolutionComponent> takersolutionComponentsForCurrItemId = new HashSet<TakersolutionComponent>(0);
	private Set<TakersolutionComponent> takersolutionComponentsForNextItemId = new HashSet<TakersolutionComponent>(0);
	private Set<QsolutionComponent> qsolutionComponentsForNextItemId = new HashSet<QsolutionComponent>(0);
	private Set<QsolutionComponent> qsolutionComponentsForCurrItemId = new HashSet<QsolutionComponent>(0);

	public QuestionItem() {
	}

	public QuestionItem(Question question, String itemCode, String itemDesc, Byte itemOrder, String itemReviewerComment,
			String itemTakerComment, Set<QuestionItemInfo> questionItemInfos, Set<FillableElement> fillableElements,
			Set<TakersolutionComponent> takersolutionComponentsForCurrItemId,
			Set<TakersolutionComponent> takersolutionComponentsForNextItemId,
			Set<QsolutionComponent> qsolutionComponentsForNextItemId,
			Set<QsolutionComponent> qsolutionComponentsForCurrItemId) {
		this.question = question;
		this.itemCode = itemCode;
		this.itemDesc = itemDesc;
		this.itemOrder = itemOrder;
		this.itemReviewerComment = itemReviewerComment;
		this.itemTakerComment = itemTakerComment;
		this.questionItemInfos = questionItemInfos;
		this.fillableElements = fillableElements;
		this.takersolutionComponentsForCurrItemId = takersolutionComponentsForCurrItemId;
		this.takersolutionComponentsForNextItemId = takersolutionComponentsForNextItemId;
		this.qsolutionComponentsForNextItemId = qsolutionComponentsForNextItemId;
		this.qsolutionComponentsForCurrItemId = qsolutionComponentsForCurrItemId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "item_id", unique = true, nullable = false)
	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_id")
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "item_code", length = 10)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "item_desc", length = 65535)
	public String getItemDesc() {
		return this.itemDesc;
	}

	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}

	@Column(name = "item_order")
	public Byte getItemOrder() {
		return this.itemOrder;
	}

	public void setItemOrder(Byte itemOrder) {
		this.itemOrder = itemOrder;
	}

	@Column(name = "item_reviewer_comment", length = 65535)
	public String getItemReviewerComment() {
		return this.itemReviewerComment;
	}

	public void setItemReviewerComment(String itemReviewerComment) {
		this.itemReviewerComment = itemReviewerComment;
	}

	@Column(name = "item_taker_comment", length = 65535)
	public String getItemTakerComment() {
		return this.itemTakerComment;
	}

	public void setItemTakerComment(String itemTakerComment) {
		this.itemTakerComment = itemTakerComment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionItem")
	public Set<QuestionItemInfo> getQuestionItemInfos() {
		return this.questionItemInfos;
	}

	public void setQuestionItemInfos(Set<QuestionItemInfo> questionItemInfos) {
		this.questionItemInfos = questionItemInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionItem")
	public Set<FillableElement> getFillableElements() {
		return this.fillableElements;
	}

	public void setFillableElements(Set<FillableElement> fillableElements) {
		this.fillableElements = fillableElements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionItemByCurrItemId")
	public Set<TakersolutionComponent> getTakersolutionComponentsForCurrItemId() {
		return this.takersolutionComponentsForCurrItemId;
	}

	public void setTakersolutionComponentsForCurrItemId(
			Set<TakersolutionComponent> takersolutionComponentsForCurrItemId) {
		this.takersolutionComponentsForCurrItemId = takersolutionComponentsForCurrItemId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionItemByNextItemId")
	public Set<TakersolutionComponent> getTakersolutionComponentsForNextItemId() {
		return this.takersolutionComponentsForNextItemId;
	}

	public void setTakersolutionComponentsForNextItemId(
			Set<TakersolutionComponent> takersolutionComponentsForNextItemId) {
		this.takersolutionComponentsForNextItemId = takersolutionComponentsForNextItemId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionItemByNextItemId")
	public Set<QsolutionComponent> getQsolutionComponentsForNextItemId() {
		return this.qsolutionComponentsForNextItemId;
	}

	public void setQsolutionComponentsForNextItemId(Set<QsolutionComponent> qsolutionComponentsForNextItemId) {
		this.qsolutionComponentsForNextItemId = qsolutionComponentsForNextItemId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionItemByCurrItemId")
	public Set<QsolutionComponent> getQsolutionComponentsForCurrItemId() {
		return this.qsolutionComponentsForCurrItemId;
	}

	public void setQsolutionComponentsForCurrItemId(Set<QsolutionComponent> qsolutionComponentsForCurrItemId) {
		this.qsolutionComponentsForCurrItemId = qsolutionComponentsForCurrItemId;
	}

}
