package com.therealdanvega.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuestionAccessMode generated by hbm2java
 */
@Entity
@Table(name = "question_access_mode", catalog = "testts")
public class QuestionAccessMode implements java.io.Serializable {

	private Integer questionAccessModeId;
	private Previlege previlege;
	private Question question;
	private Role role;
	private User userByGrantorId;
	private User userByAccessorId;
	private Date questionAccessModeGrantedDate;
	private Date questionAccessModeValidStartdate;
	private Date questionAccessModeValidEnddate;
	private Date questionAccessModeValidStarttime;
	private Date questionAccessModeValidEndtime;
	private boolean questionAccessModeIsDisabled;
	private String questionAccessModeDesc;

	public QuestionAccessMode() {
	}

	public QuestionAccessMode(User userByGrantorId, Date questionAccessModeValidStartdate,
			Date questionAccessModeValidStarttime, boolean questionAccessModeIsDisabled) {
		this.userByGrantorId = userByGrantorId;
		this.questionAccessModeValidStartdate = questionAccessModeValidStartdate;
		this.questionAccessModeValidStarttime = questionAccessModeValidStarttime;
		this.questionAccessModeIsDisabled = questionAccessModeIsDisabled;
	}

	public QuestionAccessMode(Previlege previlege, Question question, Role role, User userByGrantorId,
			User userByAccessorId, Date questionAccessModeGrantedDate, Date questionAccessModeValidStartdate,
			Date questionAccessModeValidEnddate, Date questionAccessModeValidStarttime,
			Date questionAccessModeValidEndtime, boolean questionAccessModeIsDisabled, String questionAccessModeDesc) {
		this.previlege = previlege;
		this.question = question;
		this.role = role;
		this.userByGrantorId = userByGrantorId;
		this.userByAccessorId = userByAccessorId;
		this.questionAccessModeGrantedDate = questionAccessModeGrantedDate;
		this.questionAccessModeValidStartdate = questionAccessModeValidStartdate;
		this.questionAccessModeValidEnddate = questionAccessModeValidEnddate;
		this.questionAccessModeValidStarttime = questionAccessModeValidStarttime;
		this.questionAccessModeValidEndtime = questionAccessModeValidEndtime;
		this.questionAccessModeIsDisabled = questionAccessModeIsDisabled;
		this.questionAccessModeDesc = questionAccessModeDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "question_access_mode_id", unique = true, nullable = false)
	public Integer getQuestionAccessModeId() {
		return this.questionAccessModeId;
	}

	public void setQuestionAccessModeId(Integer questionAccessModeId) {
		this.questionAccessModeId = questionAccessModeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "previlege_id")
	public Previlege getPrevilege() {
		return this.previlege;
	}

	public void setPrevilege(Previlege previlege) {
		this.previlege = previlege;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_id")
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "grantor_id", nullable = false)
	public User getUserByGrantorId() {
		return this.userByGrantorId;
	}

	public void setUserByGrantorId(User userByGrantorId) {
		this.userByGrantorId = userByGrantorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accessor_id")
	public User getUserByAccessorId() {
		return this.userByAccessorId;
	}

	public void setUserByAccessorId(User userByAccessorId) {
		this.userByAccessorId = userByAccessorId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "question_access_mode_granted_date", length = 10)
	public Date getQuestionAccessModeGrantedDate() {
		return this.questionAccessModeGrantedDate;
	}

	public void setQuestionAccessModeGrantedDate(Date questionAccessModeGrantedDate) {
		this.questionAccessModeGrantedDate = questionAccessModeGrantedDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "question_access_mode_valid_startdate", nullable = false, length = 10)
	public Date getQuestionAccessModeValidStartdate() {
		return this.questionAccessModeValidStartdate;
	}

	public void setQuestionAccessModeValidStartdate(Date questionAccessModeValidStartdate) {
		this.questionAccessModeValidStartdate = questionAccessModeValidStartdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "question_access_mode_valid_enddate", length = 10)
	public Date getQuestionAccessModeValidEnddate() {
		return this.questionAccessModeValidEnddate;
	}

	public void setQuestionAccessModeValidEnddate(Date questionAccessModeValidEnddate) {
		this.questionAccessModeValidEnddate = questionAccessModeValidEnddate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "question_access_mode_valid_starttime", nullable = false, length = 8)
	public Date getQuestionAccessModeValidStarttime() {
		return this.questionAccessModeValidStarttime;
	}

	public void setQuestionAccessModeValidStarttime(Date questionAccessModeValidStarttime) {
		this.questionAccessModeValidStarttime = questionAccessModeValidStarttime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "question_access_mode_valid_endtime", length = 8)
	public Date getQuestionAccessModeValidEndtime() {
		return this.questionAccessModeValidEndtime;
	}

	public void setQuestionAccessModeValidEndtime(Date questionAccessModeValidEndtime) {
		this.questionAccessModeValidEndtime = questionAccessModeValidEndtime;
	}

	@Column(name = "question_access_mode_is_disabled", nullable = false)
	public boolean isQuestionAccessModeIsDisabled() {
		return this.questionAccessModeIsDisabled;
	}

	public void setQuestionAccessModeIsDisabled(boolean questionAccessModeIsDisabled) {
		this.questionAccessModeIsDisabled = questionAccessModeIsDisabled;
	}

	@Column(name = "question_access_mode_desc", length = 65535)
	public String getQuestionAccessModeDesc() {
		return this.questionAccessModeDesc;
	}

	public void setQuestionAccessModeDesc(String questionAccessModeDesc) {
		this.questionAccessModeDesc = questionAccessModeDesc;
	}

}
