package com.therealdanvega.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StudentOutcomeItem generated by hbm2java
 */
@Entity
@Table(name = "student_outcome_item", catalog = "testts")
public class StudentOutcomeItem implements java.io.Serializable {

	private Integer soiId;
	private StudentOutcome studentOutcome;
	private String soiCode;
	private String soiDescVn;
	private String soiDescEn;
	private Set<PerformanceIndicatorVersion> performanceIndicatorVersions = new HashSet<PerformanceIndicatorVersion>(0);
	private Set<SoComment> soComments = new HashSet<SoComment>(0);
	private Set<CoiSoiMap> coiSoiMaps = new HashSet<CoiSoiMap>(0);
	private Set<PeoiSoiMap> peoiSoiMaps = new HashSet<PeoiSoiMap>(0);

	public StudentOutcomeItem() {
	}

	public StudentOutcomeItem(String soiCode, String soiDescVn, String soiDescEn) {
		this.soiCode = soiCode;
		this.soiDescVn = soiDescVn;
		this.soiDescEn = soiDescEn;
	}

	public StudentOutcomeItem(StudentOutcome studentOutcome, String soiCode, String soiDescVn, String soiDescEn,
			Set<PerformanceIndicatorVersion> performanceIndicatorVersions, Set<SoComment> soComments,
			Set<CoiSoiMap> coiSoiMaps, Set<PeoiSoiMap> peoiSoiMaps) {
		this.studentOutcome = studentOutcome;
		this.soiCode = soiCode;
		this.soiDescVn = soiDescVn;
		this.soiDescEn = soiDescEn;
		this.performanceIndicatorVersions = performanceIndicatorVersions;
		this.soComments = soComments;
		this.coiSoiMaps = coiSoiMaps;
		this.peoiSoiMaps = peoiSoiMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "soi_id", unique = true, nullable = false)
	public Integer getSoiId() {
		return this.soiId;
	}

	public void setSoiId(Integer soiId) {
		this.soiId = soiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "so_id")
	public StudentOutcome getStudentOutcome() {
		return this.studentOutcome;
	}

	public void setStudentOutcome(StudentOutcome studentOutcome) {
		this.studentOutcome = studentOutcome;
	}

	@Column(name = "soi_code", nullable = false, length = 2)
	public String getSoiCode() {
		return this.soiCode;
	}

	public void setSoiCode(String soiCode) {
		this.soiCode = soiCode;
	}

	@Column(name = "soi_desc_vn", nullable = false, length = 65535)
	public String getSoiDescVn() {
		return this.soiDescVn;
	}

	public void setSoiDescVn(String soiDescVn) {
		this.soiDescVn = soiDescVn;
	}

	@Column(name = "soi_desc_en", nullable = false, length = 65535)
	public String getSoiDescEn() {
		return this.soiDescEn;
	}

	public void setSoiDescEn(String soiDescEn) {
		this.soiDescEn = soiDescEn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentOutcomeItem")
	public Set<PerformanceIndicatorVersion> getPerformanceIndicatorVersions() {
		return this.performanceIndicatorVersions;
	}

	public void setPerformanceIndicatorVersions(Set<PerformanceIndicatorVersion> performanceIndicatorVersions) {
		this.performanceIndicatorVersions = performanceIndicatorVersions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentOutcomeItem")
	public Set<SoComment> getSoComments() {
		return this.soComments;
	}

	public void setSoComments(Set<SoComment> soComments) {
		this.soComments = soComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentOutcomeItem")
	public Set<CoiSoiMap> getCoiSoiMaps() {
		return this.coiSoiMaps;
	}

	public void setCoiSoiMaps(Set<CoiSoiMap> coiSoiMaps) {
		this.coiSoiMaps = coiSoiMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentOutcomeItem")
	public Set<PeoiSoiMap> getPeoiSoiMaps() {
		return this.peoiSoiMaps;
	}

	public void setPeoiSoiMaps(Set<PeoiSoiMap> peoiSoiMaps) {
		this.peoiSoiMaps = peoiSoiMaps;
	}

}
