package com.therealdanvega.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TakerSolution generated by hbm2java
 */
@Entity
@Table(name = "taker_solution", catalog = "testts")
public class TakerSolution implements java.io.Serializable {

	private Integer takerSolutionId;
	private Question question;
	private TakerTestMap takerTestMap;
	private Integer markMax;
	private Integer markCur;
	private Set<TakersolutionComponent> takersolutionComponents = new HashSet<TakersolutionComponent>(0);

	public TakerSolution() {
	}

	public TakerSolution(Question question, TakerTestMap takerTestMap, Integer markMax, Integer markCur,
			Set<TakersolutionComponent> takersolutionComponents) {
		this.question = question;
		this.takerTestMap = takerTestMap;
		this.markMax = markMax;
		this.markCur = markCur;
		this.takersolutionComponents = takersolutionComponents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "taker_solution_id", unique = true, nullable = false)
	public Integer getTakerSolutionId() {
		return this.takerSolutionId;
	}

	public void setTakerSolutionId(Integer takerSolutionId) {
		this.takerSolutionId = takerSolutionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_id")
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taker_test_map_id")
	public TakerTestMap getTakerTestMap() {
		return this.takerTestMap;
	}

	public void setTakerTestMap(TakerTestMap takerTestMap) {
		this.takerTestMap = takerTestMap;
	}

	@Column(name = "mark_max")
	public Integer getMarkMax() {
		return this.markMax;
	}

	public void setMarkMax(Integer markMax) {
		this.markMax = markMax;
	}

	@Column(name = "mark_cur")
	public Integer getMarkCur() {
		return this.markCur;
	}

	public void setMarkCur(Integer markCur) {
		this.markCur = markCur;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "takerSolution")
	public Set<TakersolutionComponent> getTakersolutionComponents() {
		return this.takersolutionComponents;
	}

	public void setTakersolutionComponents(Set<TakersolutionComponent> takersolutionComponents) {
		this.takersolutionComponents = takersolutionComponents;
	}

}
