package com.therealdanvega.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TestCommentRelationship generated by hbm2java
 */
@Entity
@Table(name = "test_comment_relationship", catalog = "testts")
public class TestCommentRelationship implements java.io.Serializable {

	private Integer testCommentRelationshipId;
	private Integer parentTestCommentId;
	private Integer childTestCommentId;
	private String testCommentRelationshipDesc;

	public TestCommentRelationship() {
	}

	public TestCommentRelationship(Integer parentTestCommentId, Integer childTestCommentId,
			String testCommentRelationshipDesc) {
		this.parentTestCommentId = parentTestCommentId;
		this.childTestCommentId = childTestCommentId;
		this.testCommentRelationshipDesc = testCommentRelationshipDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "test_comment_relationship_id", unique = true, nullable = false)
	public Integer getTestCommentRelationshipId() {
		return this.testCommentRelationshipId;
	}

	public void setTestCommentRelationshipId(Integer testCommentRelationshipId) {
		this.testCommentRelationshipId = testCommentRelationshipId;
	}

	@Column(name = "parent_test_comment_id")
	public Integer getParentTestCommentId() {
		return this.parentTestCommentId;
	}

	public void setParentTestCommentId(Integer parentTestCommentId) {
		this.parentTestCommentId = parentTestCommentId;
	}

	@Column(name = "child_test_comment_id")
	public Integer getChildTestCommentId() {
		return this.childTestCommentId;
	}

	public void setChildTestCommentId(Integer childTestCommentId) {
		this.childTestCommentId = childTestCommentId;
	}

	@Column(name = "test_comment_relationship_desc", length = 65535)
	public String getTestCommentRelationshipDesc() {
		return this.testCommentRelationshipDesc;
	}

	public void setTestCommentRelationshipDesc(String testCommentRelationshipDesc) {
		this.testCommentRelationshipDesc = testCommentRelationshipDesc;
	}

}
