package com.therealdanvega.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UnivMission generated by hbm2java
 */
@Entity
@Table(name = "univ_mission", catalog = "testts")
public class UnivMission implements java.io.Serializable {

	private Integer umId;
	private University university;
	private String umCode;
	private Date umDate;
	private boolean umIsused;
	private Set<UnivMissionItem> univMissionItems = new HashSet<UnivMissionItem>(0);
	private Set<PeoMissionMapVersion> peoMissionMapVersions = new HashSet<PeoMissionMapVersion>(0);

	public UnivMission() {
	}

	public UnivMission(String umCode, Date umDate, boolean umIsused) {
		this.umCode = umCode;
		this.umDate = umDate;
		this.umIsused = umIsused;
	}

	public UnivMission(University university, String umCode, Date umDate, boolean umIsused,
			Set<UnivMissionItem> univMissionItems, Set<PeoMissionMapVersion> peoMissionMapVersions) {
		this.university = university;
		this.umCode = umCode;
		this.umDate = umDate;
		this.umIsused = umIsused;
		this.univMissionItems = univMissionItems;
		this.peoMissionMapVersions = peoMissionMapVersions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "um_id", unique = true, nullable = false)
	public Integer getUmId() {
		return this.umId;
	}

	public void setUmId(Integer umId) {
		this.umId = umId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "univ_id")
	public University getUniversity() {
		return this.university;
	}

	public void setUniversity(University university) {
		this.university = university;
	}

	@Column(name = "um_code", nullable = false, length = 10)
	public String getUmCode() {
		return this.umCode;
	}

	public void setUmCode(String umCode) {
		this.umCode = umCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "um_date", nullable = false, length = 10)
	public Date getUmDate() {
		return this.umDate;
	}

	public void setUmDate(Date umDate) {
		this.umDate = umDate;
	}

	@Column(name = "um_isused", nullable = false)
	public boolean isUmIsused() {
		return this.umIsused;
	}

	public void setUmIsused(boolean umIsused) {
		this.umIsused = umIsused;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "univMission")
	public Set<UnivMissionItem> getUnivMissionItems() {
		return this.univMissionItems;
	}

	public void setUnivMissionItems(Set<UnivMissionItem> univMissionItems) {
		this.univMissionItems = univMissionItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "univMission")
	public Set<PeoMissionMapVersion> getPeoMissionMapVersions() {
		return this.peoMissionMapVersions;
	}

	public void setPeoMissionMapVersions(Set<PeoMissionMapVersion> peoMissionMapVersions) {
		this.peoMissionMapVersions = peoMissionMapVersions;
	}

}
