package com.therealdanvega.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * University generated by hbm2java
 */
@Entity
@Table(name = "university", catalog = "testts")
public class University implements java.io.Serializable {

	private Integer univId;
	private String univCode;
	private String univNameVn;
	private String univNameEn;
	private String univNameShort;
	private Set<Faculty> faculties = new HashSet<Faculty>(0);
	private Set<UnivMission> univMissions = new HashSet<UnivMission>(0);

	public University() {
	}

	public University(String univCode, String univNameVn, String univNameEn, String univNameShort) {
		this.univCode = univCode;
		this.univNameVn = univNameVn;
		this.univNameEn = univNameEn;
		this.univNameShort = univNameShort;
	}

	public University(String univCode, String univNameVn, String univNameEn, String univNameShort,
			Set<Faculty> faculties, Set<UnivMission> univMissions) {
		this.univCode = univCode;
		this.univNameVn = univNameVn;
		this.univNameEn = univNameEn;
		this.univNameShort = univNameShort;
		this.faculties = faculties;
		this.univMissions = univMissions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "univ_id", unique = true, nullable = false)
	public Integer getUnivId() {
		return this.univId;
	}

	public void setUnivId(Integer univId) {
		this.univId = univId;
	}

	@Column(name = "univ_code", nullable = false, length = 10)
	public String getUnivCode() {
		return this.univCode;
	}

	public void setUnivCode(String univCode) {
		this.univCode = univCode;
	}

	@Column(name = "univ_name_vn", nullable = false, length = 65535)
	public String getUnivNameVn() {
		return this.univNameVn;
	}

	public void setUnivNameVn(String univNameVn) {
		this.univNameVn = univNameVn;
	}

	@Column(name = "univ_name_en", nullable = false, length = 65535)
	public String getUnivNameEn() {
		return this.univNameEn;
	}

	public void setUnivNameEn(String univNameEn) {
		this.univNameEn = univNameEn;
	}

	@Column(name = "univ_name_short", nullable = false, length = 10)
	public String getUnivNameShort() {
		return this.univNameShort;
	}

	public void setUnivNameShort(String univNameShort) {
		this.univNameShort = univNameShort;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "university")
	public Set<Faculty> getFaculties() {
		return this.faculties;
	}

	public void setFaculties(Set<Faculty> faculties) {
		this.faculties = faculties;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "university")
	public Set<UnivMission> getUnivMissions() {
		return this.univMissions;
	}

	public void setUnivMissions(Set<UnivMission> univMissions) {
		this.univMissions = univMissions;
	}

}
