package com.therealdanvega.domain;
// Generated Mar 4, 2018 2:56:35 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserCourseDevmap generated by hbm2java
 */
@Entity
@Table(name = "user_course_devmap", catalog = "mycontact")
public class UserCourseDevmap implements java.io.Serializable {

	private Integer userCourseDevmapId;
	private Course course;
	private User user;

	public UserCourseDevmap() {
	}

	public UserCourseDevmap(Course course, User user) {
		this.course = course;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_course_devmap_id", unique = true, nullable = false)
	public Integer getUserCourseDevmapId() {
		return this.userCourseDevmapId;
	}

	public void setUserCourseDevmapId(Integer userCourseDevmapId) {
		this.userCourseDevmapId = userCourseDevmapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id")
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
