package com.congbang.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BloomLevel generated by hbm2java
 */
@Entity
@Table(name = "bloom_level", catalog = "testts")
public class BloomLevel implements java.io.Serializable {

	private Integer bloomLevelId;
	private byte bloomLevelCode;
	private String bloomLevelDesc;
	private Set<Question> questions = new HashSet<Question>(0);

	public BloomLevel() {
	}

	public BloomLevel(byte bloomLevelCode, String bloomLevelDesc) {
		this.bloomLevelCode = bloomLevelCode;
		this.bloomLevelDesc = bloomLevelDesc;
	}

	public BloomLevel(byte bloomLevelCode, String bloomLevelDesc, Set<Question> questions) {
		this.bloomLevelCode = bloomLevelCode;
		this.bloomLevelDesc = bloomLevelDesc;
		this.questions = questions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bloom_level_id", unique = true, nullable = false)
	public Integer getBloomLevelId() {
		return this.bloomLevelId;
	}

	public void setBloomLevelId(Integer bloomLevelId) {
		this.bloomLevelId = bloomLevelId;
	}

	@Column(name = "bloom_level_code", nullable = false)
	public byte getBloomLevelCode() {
		return this.bloomLevelCode;
	}

	public void setBloomLevelCode(byte bloomLevelCode) {
		this.bloomLevelCode = bloomLevelCode;
	}

	@Column(name = "bloom_level_desc", nullable = false, length = 64)
	public String getBloomLevelDesc() {
		return this.bloomLevelDesc;
	}

	public void setBloomLevelDesc(String bloomLevelDesc) {
		this.bloomLevelDesc = bloomLevelDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bloomLevel")
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

}
