package com.congbang.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CcoMap generated by hbm2java
 */
@Entity
@Table(name = "cco_map", catalog = "testts")
public class CcoMap implements java.io.Serializable {

	private Integer ccoId;
	private CourseContent courseContent;
	private CourseOutcomeItem courseOutcomeItem;
	private String ccoDesc;

	public CcoMap() {
	}

	public CcoMap(CourseContent courseContent, CourseOutcomeItem courseOutcomeItem, String ccoDesc) {
		this.courseContent = courseContent;
		this.courseOutcomeItem = courseOutcomeItem;
		this.ccoDesc = ccoDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cco_id", unique = true, nullable = false)
	public Integer getCcoId() {
		return this.ccoId;
	}

	public void setCcoId(Integer ccoId) {
		this.ccoId = ccoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cc_id")
	public CourseContent getCourseContent() {
		return this.courseContent;
	}

	public void setCourseContent(CourseContent courseContent) {
		this.courseContent = courseContent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coi_id")
	public CourseOutcomeItem getCourseOutcomeItem() {
		return this.courseOutcomeItem;
	}

	public void setCourseOutcomeItem(CourseOutcomeItem courseOutcomeItem) {
		this.courseOutcomeItem = courseOutcomeItem;
	}

	@Column(name = "cco_desc", length = 65535)
	public String getCcoDesc() {
		return this.ccoDesc;
	}

	public void setCcoDesc(String ccoDesc) {
		this.ccoDesc = ccoDesc;
	}

}
