package com.congbang.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CoiSoiMap generated by hbm2java
 */
@Entity
@Table(name = "coi_soi_map", catalog = "testts")
public class CoiSoiMap implements java.io.Serializable {

	private Integer csimId;
	private CoSoMap coSoMap;
	private CourseOutcomeItem courseOutcomeItem;
	private StudentOutcomeItem studentOutcomeItem;
	private char csimLevel;

	public CoiSoiMap() {
	}

	public CoiSoiMap(char csimLevel) {
		this.csimLevel = csimLevel;
	}

	public CoiSoiMap(CoSoMap coSoMap, CourseOutcomeItem courseOutcomeItem, StudentOutcomeItem studentOutcomeItem,
			char csimLevel) {
		this.coSoMap = coSoMap;
		this.courseOutcomeItem = courseOutcomeItem;
		this.studentOutcomeItem = studentOutcomeItem;
		this.csimLevel = csimLevel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "csim_id", unique = true, nullable = false)
	public Integer getCsimId() {
		return this.csimId;
	}

	public void setCsimId(Integer csimId) {
		this.csimId = csimId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "csom_id")
	public CoSoMap getCoSoMap() {
		return this.coSoMap;
	}

	public void setCoSoMap(CoSoMap coSoMap) {
		this.coSoMap = coSoMap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coi_id")
	public CourseOutcomeItem getCourseOutcomeItem() {
		return this.courseOutcomeItem;
	}

	public void setCourseOutcomeItem(CourseOutcomeItem courseOutcomeItem) {
		this.courseOutcomeItem = courseOutcomeItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "soi_id")
	public StudentOutcomeItem getStudentOutcomeItem() {
		return this.studentOutcomeItem;
	}

	public void setStudentOutcomeItem(StudentOutcomeItem studentOutcomeItem) {
		this.studentOutcomeItem = studentOutcomeItem;
	}

	@Column(name = "csim_level", nullable = false, length = 1)
	public char getCsimLevel() {
		return this.csimLevel;
	}

	public void setCsimLevel(char csimLevel) {
		this.csimLevel = csimLevel;
	}

}
