package com.congbang.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CoSoMap generated by hbm2java
 */
@Entity
@Table(name = "co_so_map", catalog = "testts")
public class CoSoMap implements java.io.Serializable {

	private Integer csomId;
	private CourseOutcome courseOutcome;
	private StudentOutcome studentOutcome;
	private int csomCode;
	private Date csomDate;
	private boolean csomIsused;
	private Set<CoiSoiMap> coiSoiMaps = new HashSet<CoiSoiMap>(0);

	public CoSoMap() {
	}

	public CoSoMap(int csomCode, Date csomDate, boolean csomIsused) {
		this.csomCode = csomCode;
		this.csomDate = csomDate;
		this.csomIsused = csomIsused;
	}

	public CoSoMap(CourseOutcome courseOutcome, StudentOutcome studentOutcome, int csomCode, Date csomDate,
			boolean csomIsused, Set<CoiSoiMap> coiSoiMaps) {
		this.courseOutcome = courseOutcome;
		this.studentOutcome = studentOutcome;
		this.csomCode = csomCode;
		this.csomDate = csomDate;
		this.csomIsused = csomIsused;
		this.coiSoiMaps = coiSoiMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "csom_id", unique = true, nullable = false)
	public Integer getCsomId() {
		return this.csomId;
	}

	public void setCsomId(Integer csomId) {
		this.csomId = csomId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "co_id")
	public CourseOutcome getCourseOutcome() {
		return this.courseOutcome;
	}

	public void setCourseOutcome(CourseOutcome courseOutcome) {
		this.courseOutcome = courseOutcome;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "so_id")
	public StudentOutcome getStudentOutcome() {
		return this.studentOutcome;
	}

	public void setStudentOutcome(StudentOutcome studentOutcome) {
		this.studentOutcome = studentOutcome;
	}

	@Column(name = "csom_code", nullable = false)
	public int getCsomCode() {
		return this.csomCode;
	}

	public void setCsomCode(int csomCode) {
		this.csomCode = csomCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "csom_date", nullable = false, length = 10)
	public Date getCsomDate() {
		return this.csomDate;
	}

	public void setCsomDate(Date csomDate) {
		this.csomDate = csomDate;
	}

	@Column(name = "csom_isused", nullable = false)
	public boolean isCsomIsused() {
		return this.csomIsused;
	}

	public void setCsomIsused(boolean csomIsused) {
		this.csomIsused = csomIsused;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coSoMap")
	public Set<CoiSoiMap> getCoiSoiMaps() {
		return this.coiSoiMaps;
	}

	public void setCoiSoiMaps(Set<CoiSoiMap> coiSoiMaps) {
		this.coiSoiMaps = coiSoiMaps;
	}

}
