package com.congbang.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CoSoR4trData generated by hbm2java
 */
@Entity
@Table(name = "_co_so_r4tr_data", catalog = "testts")
public class CoSoR4trData implements java.io.Serializable {

	private int coiId;
	private Integer soi2;
	private Integer soi2Total;
	private Integer soi3;
	private Integer soi3Total;
	private Integer soi4;
	private Integer soi4Total;
	private Integer soi5;
	private Integer soi5Total;
	private Integer soi6;
	private Integer soi6Total;
	private Integer soi7;
	private Integer soi7Total;
	private Integer soi8;
	private Integer soi8Total;
	private Integer soi9;
	private Integer soi9Total;
	private Integer soi10;
	private Integer soi10Total;
	private Integer soi11;
	private Integer soi11Total;
	private Integer soi12;
	private Integer soi12Total;
	private Integer soi13;
	private Integer soi13Total;

	public CoSoR4trData() {
	}

	public CoSoR4trData(int coiId) {
		this.coiId = coiId;
	}

	public CoSoR4trData(int coiId, Integer soi2, Integer soi2Total, Integer soi3, Integer soi3Total, Integer soi4,
			Integer soi4Total, Integer soi5, Integer soi5Total, Integer soi6, Integer soi6Total, Integer soi7,
			Integer soi7Total, Integer soi8, Integer soi8Total, Integer soi9, Integer soi9Total, Integer soi10,
			Integer soi10Total, Integer soi11, Integer soi11Total, Integer soi12, Integer soi12Total, Integer soi13,
			Integer soi13Total) {
		this.coiId = coiId;
		this.soi2 = soi2;
		this.soi2Total = soi2Total;
		this.soi3 = soi3;
		this.soi3Total = soi3Total;
		this.soi4 = soi4;
		this.soi4Total = soi4Total;
		this.soi5 = soi5;
		this.soi5Total = soi5Total;
		this.soi6 = soi6;
		this.soi6Total = soi6Total;
		this.soi7 = soi7;
		this.soi7Total = soi7Total;
		this.soi8 = soi8;
		this.soi8Total = soi8Total;
		this.soi9 = soi9;
		this.soi9Total = soi9Total;
		this.soi10 = soi10;
		this.soi10Total = soi10Total;
		this.soi11 = soi11;
		this.soi11Total = soi11Total;
		this.soi12 = soi12;
		this.soi12Total = soi12Total;
		this.soi13 = soi13;
		this.soi13Total = soi13Total;
	}

	@Id

	@Column(name = "coi_id", unique = true, nullable = false)
	public int getCoiId() {
		return this.coiId;
	}

	public void setCoiId(int coiId) {
		this.coiId = coiId;
	}

	@Column(name = "soi_2")
	public Integer getSoi2() {
		return this.soi2;
	}

	public void setSoi2(Integer soi2) {
		this.soi2 = soi2;
	}

	@Column(name = "soi_2_total")
	public Integer getSoi2Total() {
		return this.soi2Total;
	}

	public void setSoi2Total(Integer soi2Total) {
		this.soi2Total = soi2Total;
	}

	@Column(name = "soi_3")
	public Integer getSoi3() {
		return this.soi3;
	}

	public void setSoi3(Integer soi3) {
		this.soi3 = soi3;
	}

	@Column(name = "soi_3_total")
	public Integer getSoi3Total() {
		return this.soi3Total;
	}

	public void setSoi3Total(Integer soi3Total) {
		this.soi3Total = soi3Total;
	}

	@Column(name = "soi_4")
	public Integer getSoi4() {
		return this.soi4;
	}

	public void setSoi4(Integer soi4) {
		this.soi4 = soi4;
	}

	@Column(name = "soi_4_total")
	public Integer getSoi4Total() {
		return this.soi4Total;
	}

	public void setSoi4Total(Integer soi4Total) {
		this.soi4Total = soi4Total;
	}

	@Column(name = "soi_5")
	public Integer getSoi5() {
		return this.soi5;
	}

	public void setSoi5(Integer soi5) {
		this.soi5 = soi5;
	}

	@Column(name = "soi_5_total")
	public Integer getSoi5Total() {
		return this.soi5Total;
	}

	public void setSoi5Total(Integer soi5Total) {
		this.soi5Total = soi5Total;
	}

	@Column(name = "soi_6")
	public Integer getSoi6() {
		return this.soi6;
	}

	public void setSoi6(Integer soi6) {
		this.soi6 = soi6;
	}

	@Column(name = "soi_6_total")
	public Integer getSoi6Total() {
		return this.soi6Total;
	}

	public void setSoi6Total(Integer soi6Total) {
		this.soi6Total = soi6Total;
	}

	@Column(name = "soi_7")
	public Integer getSoi7() {
		return this.soi7;
	}

	public void setSoi7(Integer soi7) {
		this.soi7 = soi7;
	}

	@Column(name = "soi_7_total")
	public Integer getSoi7Total() {
		return this.soi7Total;
	}

	public void setSoi7Total(Integer soi7Total) {
		this.soi7Total = soi7Total;
	}

	@Column(name = "soi_8")
	public Integer getSoi8() {
		return this.soi8;
	}

	public void setSoi8(Integer soi8) {
		this.soi8 = soi8;
	}

	@Column(name = "soi_8_total")
	public Integer getSoi8Total() {
		return this.soi8Total;
	}

	public void setSoi8Total(Integer soi8Total) {
		this.soi8Total = soi8Total;
	}

	@Column(name = "soi_9")
	public Integer getSoi9() {
		return this.soi9;
	}

	public void setSoi9(Integer soi9) {
		this.soi9 = soi9;
	}

	@Column(name = "soi_9_total")
	public Integer getSoi9Total() {
		return this.soi9Total;
	}

	public void setSoi9Total(Integer soi9Total) {
		this.soi9Total = soi9Total;
	}

	@Column(name = "soi_10")
	public Integer getSoi10() {
		return this.soi10;
	}

	public void setSoi10(Integer soi10) {
		this.soi10 = soi10;
	}

	@Column(name = "soi_10_total")
	public Integer getSoi10Total() {
		return this.soi10Total;
	}

	public void setSoi10Total(Integer soi10Total) {
		this.soi10Total = soi10Total;
	}

	@Column(name = "soi_11")
	public Integer getSoi11() {
		return this.soi11;
	}

	public void setSoi11(Integer soi11) {
		this.soi11 = soi11;
	}

	@Column(name = "soi_11_total")
	public Integer getSoi11Total() {
		return this.soi11Total;
	}

	public void setSoi11Total(Integer soi11Total) {
		this.soi11Total = soi11Total;
	}

	@Column(name = "soi_12")
	public Integer getSoi12() {
		return this.soi12;
	}

	public void setSoi12(Integer soi12) {
		this.soi12 = soi12;
	}

	@Column(name = "soi_12_total")
	public Integer getSoi12Total() {
		return this.soi12Total;
	}

	public void setSoi12Total(Integer soi12Total) {
		this.soi12Total = soi12Total;
	}

	@Column(name = "soi_13")
	public Integer getSoi13() {
		return this.soi13;
	}

	public void setSoi13(Integer soi13) {
		this.soi13 = soi13;
	}

	@Column(name = "soi_13_total")
	public Integer getSoi13Total() {
		return this.soi13Total;
	}

	public void setSoi13Total(Integer soi13Total) {
		this.soi13Total = soi13Total;
	}

}
