package com.congbang.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CourseOutcome generated by hbm2java
 */
@Entity
@Table(name = "course_outcome", catalog = "testts")
public class CourseOutcome implements java.io.Serializable {

	private Integer coId;
	private Course course;
	private String coCode;
	private Date coDate;
	private boolean coIsused;
	private Set<CourseOutcomeItem> courseOutcomeItems = new HashSet<CourseOutcomeItem>(0);
	private Set<CoSoMap> coSoMaps = new HashSet<CoSoMap>(0);

	public CourseOutcome() {
	}

	public CourseOutcome(String coCode, Date coDate, boolean coIsused) {
		this.coCode = coCode;
		this.coDate = coDate;
		this.coIsused = coIsused;
	}

	public CourseOutcome(Course course, String coCode, Date coDate, boolean coIsused,
			Set<CourseOutcomeItem> courseOutcomeItems, Set<CoSoMap> coSoMaps) {
		this.course = course;
		this.coCode = coCode;
		this.coDate = coDate;
		this.coIsused = coIsused;
		this.courseOutcomeItems = courseOutcomeItems;
		this.coSoMaps = coSoMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "co_id", unique = true, nullable = false)
	public Integer getCoId() {
		return this.coId;
	}

	public void setCoId(Integer coId) {
		this.coId = coId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id")
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "co_code", nullable = false, length = 10)
	public String getCoCode() {
		return this.coCode;
	}

	public void setCoCode(String coCode) {
		this.coCode = coCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "co_date", nullable = false, length = 10)
	public Date getCoDate() {
		return this.coDate;
	}

	public void setCoDate(Date coDate) {
		this.coDate = coDate;
	}

	@Column(name = "co_isused", nullable = false)
	public boolean isCoIsused() {
		return this.coIsused;
	}

	public void setCoIsused(boolean coIsused) {
		this.coIsused = coIsused;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseOutcome")
	public Set<CourseOutcomeItem> getCourseOutcomeItems() {
		return this.courseOutcomeItems;
	}

	public void setCourseOutcomeItems(Set<CourseOutcomeItem> courseOutcomeItems) {
		this.courseOutcomeItems = courseOutcomeItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseOutcome")
	public Set<CoSoMap> getCoSoMaps() {
		return this.coSoMaps;
	}

	public void setCoSoMaps(Set<CoSoMap> coSoMaps) {
		this.coSoMaps = coSoMaps;
	}

}
