package com.congbang.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CourseOutcomeItem generated by hbm2java
 */
@Entity
@Table(name = "course_outcome_item", catalog = "testts")
public class CourseOutcomeItem implements java.io.Serializable {

	private Integer coiId;
	private CourseOutcome courseOutcome;
	private String coiCode;
	private String coiDescVn;
	private String coiDescEn;
	private Set<CoiSoiMap> coiSoiMaps = new HashSet<CoiSoiMap>(0);
	private Set<QcoMap> qcoMaps = new HashSet<QcoMap>(0);
	private Set<CcoMap> ccoMaps = new HashSet<CcoMap>(0);

	public CourseOutcomeItem() {
	}

	public CourseOutcomeItem(String coiCode, String coiDescVn) {
		this.coiCode = coiCode;
		this.coiDescVn = coiDescVn;
	}

	public CourseOutcomeItem(CourseOutcome courseOutcome, String coiCode, String coiDescVn, String coiDescEn,
			Set<CoiSoiMap> coiSoiMaps, Set<QcoMap> qcoMaps, Set<CcoMap> ccoMaps) {
		this.courseOutcome = courseOutcome;
		this.coiCode = coiCode;
		this.coiDescVn = coiDescVn;
		this.coiDescEn = coiDescEn;
		this.coiSoiMaps = coiSoiMaps;
		this.qcoMaps = qcoMaps;
		this.ccoMaps = ccoMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "coi_id", unique = true, nullable = false)
	public Integer getCoiId() {
		return this.coiId;
	}

	public void setCoiId(Integer coiId) {
		this.coiId = coiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "co_id")
	public CourseOutcome getCourseOutcome() {
		return this.courseOutcome;
	}

	public void setCourseOutcome(CourseOutcome courseOutcome) {
		this.courseOutcome = courseOutcome;
	}

	@Column(name = "coi_code", nullable = false, length = 5)
	public String getCoiCode() {
		return this.coiCode;
	}

	public void setCoiCode(String coiCode) {
		this.coiCode = coiCode;
	}

	@Column(name = "coi_desc_vn", nullable = false, length = 65535)
	public String getCoiDescVn() {
		return this.coiDescVn;
	}

	public void setCoiDescVn(String coiDescVn) {
		this.coiDescVn = coiDescVn;
	}

	@Column(name = "coi_desc_en", length = 65535)
	public String getCoiDescEn() {
		return this.coiDescEn;
	}

	public void setCoiDescEn(String coiDescEn) {
		this.coiDescEn = coiDescEn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseOutcomeItem")
	public Set<CoiSoiMap> getCoiSoiMaps() {
		return this.coiSoiMaps;
	}

	public void setCoiSoiMaps(Set<CoiSoiMap> coiSoiMaps) {
		this.coiSoiMaps = coiSoiMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseOutcomeItem")
	public Set<QcoMap> getQcoMaps() {
		return this.qcoMaps;
	}

	public void setQcoMaps(Set<QcoMap> qcoMaps) {
		this.qcoMaps = qcoMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseOutcomeItem")
	public Set<CcoMap> getCcoMaps() {
		return this.ccoMaps;
	}

	public void setCcoMaps(Set<CcoMap> ccoMaps) {
		this.ccoMaps = ccoMaps;
	}

}
