package com.congbang.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Genrandtest generated by hbm2java
 */
@Entity
@Table(name = "_genrandtest", catalog = "testts")
public class Genrandtest implements java.io.Serializable {

	private GenrandtestId id;

	public Genrandtest() {
	}

	public Genrandtest(GenrandtestId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "coiId", column = @Column(name = "coi_id")),
			@AttributeOverride(name = "qcount", column = @Column(name = "qcount", nullable = false)),
			@AttributeOverride(name = "flag", column = @Column(name = "flag", nullable = false)),
			@AttributeOverride(name = "total", column = @Column(name = "total", nullable = false)) })
	public GenrandtestId getId() {
		return this.id;
	}

	public void setId(GenrandtestId id) {
		this.id = id;
	}

}
