package com.congbang.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PeoItem generated by hbm2java
 */
@Entity
@Table(name = "peo_item", catalog = "testts")
public class PeoItem implements java.io.Serializable {

	private Integer peoiId;
	private Peo peo;
	private String peoiCode;
	private String peoiDescVn;
	private String peoiDescEn;
	private Set<UmiPeoiMap> umiPeoiMaps = new HashSet<UmiPeoiMap>(0);
	private Set<PeoComment> peoComments = new HashSet<PeoComment>(0);
	private Set<PeoiSoiMap> peoiSoiMaps = new HashSet<PeoiSoiMap>(0);

	public PeoItem() {
	}

	public PeoItem(String peoiCode, String peoiDescVn, String peoiDescEn) {
		this.peoiCode = peoiCode;
		this.peoiDescVn = peoiDescVn;
		this.peoiDescEn = peoiDescEn;
	}

	public PeoItem(Peo peo, String peoiCode, String peoiDescVn, String peoiDescEn, Set<UmiPeoiMap> umiPeoiMaps,
			Set<PeoComment> peoComments, Set<PeoiSoiMap> peoiSoiMaps) {
		this.peo = peo;
		this.peoiCode = peoiCode;
		this.peoiDescVn = peoiDescVn;
		this.peoiDescEn = peoiDescEn;
		this.umiPeoiMaps = umiPeoiMaps;
		this.peoComments = peoComments;
		this.peoiSoiMaps = peoiSoiMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "peoi_id", unique = true, nullable = false)
	public Integer getPeoiId() {
		return this.peoiId;
	}

	public void setPeoiId(Integer peoiId) {
		this.peoiId = peoiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "peo_id")
	public Peo getPeo() {
		return this.peo;
	}

	public void setPeo(Peo peo) {
		this.peo = peo;
	}

	@Column(name = "peoi_code", nullable = false, length = 5)
	public String getPeoiCode() {
		return this.peoiCode;
	}

	public void setPeoiCode(String peoiCode) {
		this.peoiCode = peoiCode;
	}

	@Column(name = "peoi_desc_vn", nullable = false, length = 65535)
	public String getPeoiDescVn() {
		return this.peoiDescVn;
	}

	public void setPeoiDescVn(String peoiDescVn) {
		this.peoiDescVn = peoiDescVn;
	}

	@Column(name = "peoi_desc_en", nullable = false, length = 65535)
	public String getPeoiDescEn() {
		return this.peoiDescEn;
	}

	public void setPeoiDescEn(String peoiDescEn) {
		this.peoiDescEn = peoiDescEn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "peoItem")
	public Set<UmiPeoiMap> getUmiPeoiMaps() {
		return this.umiPeoiMaps;
	}

	public void setUmiPeoiMaps(Set<UmiPeoiMap> umiPeoiMaps) {
		this.umiPeoiMaps = umiPeoiMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "peoItem")
	public Set<PeoComment> getPeoComments() {
		return this.peoComments;
	}

	public void setPeoComments(Set<PeoComment> peoComments) {
		this.peoComments = peoComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "peoItem")
	public Set<PeoiSoiMap> getPeoiSoiMaps() {
		return this.peoiSoiMaps;
	}

	public void setPeoiSoiMaps(Set<PeoiSoiMap> peoiSoiMaps) {
		this.peoiSoiMaps = peoiSoiMaps;
	}

}
