package com.congbang.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PeoMissionMapVersion generated by hbm2java
 */
@Entity
@Table(name = "peo_mission_map_version", catalog = "testts")
public class PeoMissionMapVersion implements java.io.Serializable {

	private Integer pmvId;
	private Peo peo;
	private UnivMission univMission;
	private int pmvCode;
	private Date pmvDate;
	private boolean pmvIsused;
	private Set<UmiPeoiMap> umiPeoiMaps = new HashSet<UmiPeoiMap>(0);

	public PeoMissionMapVersion() {
	}

	public PeoMissionMapVersion(int pmvCode, Date pmvDate, boolean pmvIsused) {
		this.pmvCode = pmvCode;
		this.pmvDate = pmvDate;
		this.pmvIsused = pmvIsused;
	}

	public PeoMissionMapVersion(Peo peo, UnivMission univMission, int pmvCode, Date pmvDate, boolean pmvIsused,
			Set<UmiPeoiMap> umiPeoiMaps) {
		this.peo = peo;
		this.univMission = univMission;
		this.pmvCode = pmvCode;
		this.pmvDate = pmvDate;
		this.pmvIsused = pmvIsused;
		this.umiPeoiMaps = umiPeoiMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pmv_id", unique = true, nullable = false)
	public Integer getPmvId() {
		return this.pmvId;
	}

	public void setPmvId(Integer pmvId) {
		this.pmvId = pmvId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "peo_version_id")
	public Peo getPeo() {
		return this.peo;
	}

	public void setPeo(Peo peo) {
		this.peo = peo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "umv_id")
	public UnivMission getUnivMission() {
		return this.univMission;
	}

	public void setUnivMission(UnivMission univMission) {
		this.univMission = univMission;
	}

	@Column(name = "pmv_code", nullable = false)
	public int getPmvCode() {
		return this.pmvCode;
	}

	public void setPmvCode(int pmvCode) {
		this.pmvCode = pmvCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pmv_date", nullable = false, length = 10)
	public Date getPmvDate() {
		return this.pmvDate;
	}

	public void setPmvDate(Date pmvDate) {
		this.pmvDate = pmvDate;
	}

	@Column(name = "pmv_isused", nullable = false)
	public boolean isPmvIsused() {
		return this.pmvIsused;
	}

	public void setPmvIsused(boolean pmvIsused) {
		this.pmvIsused = pmvIsused;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "peoMissionMapVersion")
	public Set<UmiPeoiMap> getUmiPeoiMaps() {
		return this.umiPeoiMaps;
	}

	public void setUmiPeoiMaps(Set<UmiPeoiMap> umiPeoiMaps) {
		this.umiPeoiMaps = umiPeoiMaps;
	}

}
