package com.congbang.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Previlege generated by hbm2java
 */
@Entity
@Table(name = "previlege", catalog = "testts")
public class Previlege implements java.io.Serializable {

	private Integer previlegeId;
	private String previlegeCode;
	private String previlegeDesc;
	private Set<TestAccessMode> testAccessModes = new HashSet<TestAccessMode>(0);
	private Set<TopicAccessMode> topicAccessModes = new HashSet<TopicAccessMode>(0);
	private Set<RolePrevilegeMap> rolePrevilegeMaps = new HashSet<RolePrevilegeMap>(0);
	private Set<PrevilegeRelstionship> previlegeRelstionshipsForParentPrevilegeId = new HashSet<PrevilegeRelstionship>(
			0);
	private Set<PrevilegeRelstionship> previlegeRelstionshipsForChildPrevilegeId = new HashSet<PrevilegeRelstionship>(
			0);
	private Set<ProgramAccessMode> programAccessModes = new HashSet<ProgramAccessMode>(0);
	private Set<CourseAccessMode> courseAccessModes = new HashSet<CourseAccessMode>(0);
	private Set<QuestionAccessMode> questionAccessModes = new HashSet<QuestionAccessMode>(0);

	public Previlege() {
	}

	public Previlege(String previlegeCode, String previlegeDesc) {
		this.previlegeCode = previlegeCode;
		this.previlegeDesc = previlegeDesc;
	}

	public Previlege(String previlegeCode, String previlegeDesc, Set<TestAccessMode> testAccessModes,
			Set<TopicAccessMode> topicAccessModes, Set<RolePrevilegeMap> rolePrevilegeMaps,
			Set<PrevilegeRelstionship> previlegeRelstionshipsForParentPrevilegeId,
			Set<PrevilegeRelstionship> previlegeRelstionshipsForChildPrevilegeId,
			Set<ProgramAccessMode> programAccessModes, Set<CourseAccessMode> courseAccessModes,
			Set<QuestionAccessMode> questionAccessModes) {
		this.previlegeCode = previlegeCode;
		this.previlegeDesc = previlegeDesc;
		this.testAccessModes = testAccessModes;
		this.topicAccessModes = topicAccessModes;
		this.rolePrevilegeMaps = rolePrevilegeMaps;
		this.previlegeRelstionshipsForParentPrevilegeId = previlegeRelstionshipsForParentPrevilegeId;
		this.previlegeRelstionshipsForChildPrevilegeId = previlegeRelstionshipsForChildPrevilegeId;
		this.programAccessModes = programAccessModes;
		this.courseAccessModes = courseAccessModes;
		this.questionAccessModes = questionAccessModes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "previlege_id", unique = true, nullable = false)
	public Integer getPrevilegeId() {
		return this.previlegeId;
	}

	public void setPrevilegeId(Integer previlegeId) {
		this.previlegeId = previlegeId;
	}

	@Column(name = "previlege_code", nullable = false, length = 100)
	public String getPrevilegeCode() {
		return this.previlegeCode;
	}

	public void setPrevilegeCode(String previlegeCode) {
		this.previlegeCode = previlegeCode;
	}

	@Column(name = "previlege_desc", nullable = false, length = 65535)
	public String getPrevilegeDesc() {
		return this.previlegeDesc;
	}

	public void setPrevilegeDesc(String previlegeDesc) {
		this.previlegeDesc = previlegeDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "previlege")
	public Set<TestAccessMode> getTestAccessModes() {
		return this.testAccessModes;
	}

	public void setTestAccessModes(Set<TestAccessMode> testAccessModes) {
		this.testAccessModes = testAccessModes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "previlege")
	public Set<TopicAccessMode> getTopicAccessModes() {
		return this.topicAccessModes;
	}

	public void setTopicAccessModes(Set<TopicAccessMode> topicAccessModes) {
		this.topicAccessModes = topicAccessModes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "previlege")
	public Set<RolePrevilegeMap> getRolePrevilegeMaps() {
		return this.rolePrevilegeMaps;
	}

	public void setRolePrevilegeMaps(Set<RolePrevilegeMap> rolePrevilegeMaps) {
		this.rolePrevilegeMaps = rolePrevilegeMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "previlegeByParentPrevilegeId")
	public Set<PrevilegeRelstionship> getPrevilegeRelstionshipsForParentPrevilegeId() {
		return this.previlegeRelstionshipsForParentPrevilegeId;
	}

	public void setPrevilegeRelstionshipsForParentPrevilegeId(
			Set<PrevilegeRelstionship> previlegeRelstionshipsForParentPrevilegeId) {
		this.previlegeRelstionshipsForParentPrevilegeId = previlegeRelstionshipsForParentPrevilegeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "previlegeByChildPrevilegeId")
	public Set<PrevilegeRelstionship> getPrevilegeRelstionshipsForChildPrevilegeId() {
		return this.previlegeRelstionshipsForChildPrevilegeId;
	}

	public void setPrevilegeRelstionshipsForChildPrevilegeId(
			Set<PrevilegeRelstionship> previlegeRelstionshipsForChildPrevilegeId) {
		this.previlegeRelstionshipsForChildPrevilegeId = previlegeRelstionshipsForChildPrevilegeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "previlege")
	public Set<ProgramAccessMode> getProgramAccessModes() {
		return this.programAccessModes;
	}

	public void setProgramAccessModes(Set<ProgramAccessMode> programAccessModes) {
		this.programAccessModes = programAccessModes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "previlege")
	public Set<CourseAccessMode> getCourseAccessModes() {
		return this.courseAccessModes;
	}

	public void setCourseAccessModes(Set<CourseAccessMode> courseAccessModes) {
		this.courseAccessModes = courseAccessModes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "previlege")
	public Set<QuestionAccessMode> getQuestionAccessModes() {
		return this.questionAccessModes;
	}

	public void setQuestionAccessModes(Set<QuestionAccessMode> questionAccessModes) {
		this.questionAccessModes = questionAccessModes;
	}

}
