package com.congbang.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UmiPeoiMap generated by hbm2java
 */
@Entity
@Table(name = "umi_peoi_map", catalog = "testts")
public class UmiPeoiMap implements java.io.Serializable {

	private Integer upmId;
	private PeoItem peoItem;
	private PeoMissionMapVersion peoMissionMapVersion;
	private UnivMissionItem univMissionItem;

	public UmiPeoiMap() {
	}

	public UmiPeoiMap(PeoItem peoItem, PeoMissionMapVersion peoMissionMapVersion, UnivMissionItem univMissionItem) {
		this.peoItem = peoItem;
		this.peoMissionMapVersion = peoMissionMapVersion;
		this.univMissionItem = univMissionItem;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "upm_id", unique = true, nullable = false)
	public Integer getUpmId() {
		return this.upmId;
	}

	public void setUpmId(Integer upmId) {
		this.upmId = upmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "peoi_id")
	public PeoItem getPeoItem() {
		return this.peoItem;
	}

	public void setPeoItem(PeoItem peoItem) {
		this.peoItem = peoItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pmv_id")
	public PeoMissionMapVersion getPeoMissionMapVersion() {
		return this.peoMissionMapVersion;
	}

	public void setPeoMissionMapVersion(PeoMissionMapVersion peoMissionMapVersion) {
		this.peoMissionMapVersion = peoMissionMapVersion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "umi_id")
	public UnivMissionItem getUnivMissionItem() {
		return this.univMissionItem;
	}

	public void setUnivMissionItem(UnivMissionItem univMissionItem) {
		this.univMissionItem = univMissionItem;
	}

}
