package com.congbang.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UnivMissionItem generated by hbm2java
 */
@Entity
@Table(name = "univ_mission_item", catalog = "testts")
public class UnivMissionItem implements java.io.Serializable {

	private Integer umiId;
	private UnivMission univMission;
	private String umiCode;
	private String umiDescVn;
	private String umiDescEn;
	private Set<UmiPeoiMap> umiPeoiMaps = new HashSet<UmiPeoiMap>(0);

	public UnivMissionItem() {
	}

	public UnivMissionItem(String umiCode, String umiDescVn, String umiDescEn) {
		this.umiCode = umiCode;
		this.umiDescVn = umiDescVn;
		this.umiDescEn = umiDescEn;
	}

	public UnivMissionItem(UnivMission univMission, String umiCode, String umiDescVn, String umiDescEn,
			Set<UmiPeoiMap> umiPeoiMaps) {
		this.univMission = univMission;
		this.umiCode = umiCode;
		this.umiDescVn = umiDescVn;
		this.umiDescEn = umiDescEn;
		this.umiPeoiMaps = umiPeoiMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "umi_id", unique = true, nullable = false)
	public Integer getUmiId() {
		return this.umiId;
	}

	public void setUmiId(Integer umiId) {
		this.umiId = umiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "um_id")
	public UnivMission getUnivMission() {
		return this.univMission;
	}

	public void setUnivMission(UnivMission univMission) {
		this.univMission = univMission;
	}

	@Column(name = "umi_code", nullable = false, length = 5)
	public String getUmiCode() {
		return this.umiCode;
	}

	public void setUmiCode(String umiCode) {
		this.umiCode = umiCode;
	}

	@Column(name = "umi_desc_vn", nullable = false, length = 65535)
	public String getUmiDescVn() {
		return this.umiDescVn;
	}

	public void setUmiDescVn(String umiDescVn) {
		this.umiDescVn = umiDescVn;
	}

	@Column(name = "umi_desc_en", nullable = false, length = 65535)
	public String getUmiDescEn() {
		return this.umiDescEn;
	}

	public void setUmiDescEn(String umiDescEn) {
		this.umiDescEn = umiDescEn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "univMissionItem")
	public Set<UmiPeoiMap> getUmiPeoiMaps() {
		return this.umiPeoiMaps;
	}

	public void setUmiPeoiMaps(Set<UmiPeoiMap> umiPeoiMaps) {
		this.umiPeoiMaps = umiPeoiMaps;
	}

}
