package com.congbang.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserAccount generated by hbm2java
 */
@Entity
@Table(name = "user_account", catalog = "testts")
public class UserAccount implements java.io.Serializable {

	private String accountId;
	private User user;
	private String accountPassword;
	private Set<UserAccountRoleMap> userAccountRoleMaps = new HashSet<UserAccountRoleMap>(0);

	public UserAccount() {
	}

	public UserAccount(String accountId, User user, String accountPassword) {
		this.accountId = accountId;
		this.user = user;
		this.accountPassword = accountPassword;
	}

	public UserAccount(String accountId, User user, String accountPassword,
			Set<UserAccountRoleMap> userAccountRoleMaps) {
		this.accountId = accountId;
		this.user = user;
		this.accountPassword = accountPassword;
		this.userAccountRoleMaps = userAccountRoleMaps;
	}

	@Id

	@Column(name = "account_id", unique = true, nullable = false, length = 100)
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "account_password", nullable = false, length = 65535)
	public String getAccountPassword() {
		return this.accountPassword;
	}

	public void setAccountPassword(String accountPassword) {
		this.accountPassword = accountPassword;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccount")
	public Set<UserAccountRoleMap> getUserAccountRoleMaps() {
		return this.userAccountRoleMaps;
	}

	public void setUserAccountRoleMaps(Set<UserAccountRoleMap> userAccountRoleMaps) {
		this.userAccountRoleMaps = userAccountRoleMaps;
	}

}
