package com.congbang.domain;
// Generated Apr 14, 2018 9:37:20 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewQuestionInCourseId generated by hbm2java
 */
@Embeddable
public class ViewQuestionInCourseId implements java.io.Serializable {

	private int courseContentId;
	private Integer courseId;
	private int questionId;
	private int questionTypeId;
	private Integer userId;
	private int bloomLevelId;
	private String questionDesc;
	private Boolean questionInTest;

	public ViewQuestionInCourseId() {
	}

	public ViewQuestionInCourseId(int courseContentId, int questionId, int questionTypeId, int bloomLevelId) {
		this.courseContentId = courseContentId;
		this.questionId = questionId;
		this.questionTypeId = questionTypeId;
		this.bloomLevelId = bloomLevelId;
	}

	public ViewQuestionInCourseId(int courseContentId, Integer courseId, int questionId, int questionTypeId,
			Integer userId, int bloomLevelId, String questionDesc, Boolean questionInTest) {
		this.courseContentId = courseContentId;
		this.courseId = courseId;
		this.questionId = questionId;
		this.questionTypeId = questionTypeId;
		this.userId = userId;
		this.bloomLevelId = bloomLevelId;
		this.questionDesc = questionDesc;
		this.questionInTest = questionInTest;
	}

	@Column(name = "course_content_id", nullable = false)
	public int getCourseContentId() {
		return this.courseContentId;
	}

	public void setCourseContentId(int courseContentId) {
		this.courseContentId = courseContentId;
	}

	@Column(name = "course_id")
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "question_id", nullable = false)
	public int getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

	@Column(name = "question_type_id", nullable = false)
	public int getQuestionTypeId() {
		return this.questionTypeId;
	}

	public void setQuestionTypeId(int questionTypeId) {
		this.questionTypeId = questionTypeId;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "bloom_level_id", nullable = false)
	public int getBloomLevelId() {
		return this.bloomLevelId;
	}

	public void setBloomLevelId(int bloomLevelId) {
		this.bloomLevelId = bloomLevelId;
	}

	@Column(name = "question_desc", length = 65535)
	public String getQuestionDesc() {
		return this.questionDesc;
	}

	public void setQuestionDesc(String questionDesc) {
		this.questionDesc = questionDesc;
	}

	@Column(name = "question_in_test")
	public Boolean getQuestionInTest() {
		return this.questionInTest;
	}

	public void setQuestionInTest(Boolean questionInTest) {
		this.questionInTest = questionInTest;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewQuestionInCourseId))
			return false;
		ViewQuestionInCourseId castOther = (ViewQuestionInCourseId) other;

		return (this.getCourseContentId() == castOther.getCourseContentId())
				&& ((this.getCourseId() == castOther.getCourseId()) || (this.getCourseId() != null
						&& castOther.getCourseId() != null && this.getCourseId().equals(castOther.getCourseId())))
				&& (this.getQuestionId() == castOther.getQuestionId())
				&& (this.getQuestionTypeId() == castOther.getQuestionTypeId())
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& (this.getBloomLevelId() == castOther.getBloomLevelId())
				&& ((this.getQuestionDesc() == castOther.getQuestionDesc())
						|| (this.getQuestionDesc() != null && castOther.getQuestionDesc() != null
								&& this.getQuestionDesc().equals(castOther.getQuestionDesc())))
				&& ((this.getQuestionInTest() == castOther.getQuestionInTest())
						|| (this.getQuestionInTest() != null && castOther.getQuestionInTest() != null
								&& this.getQuestionInTest().equals(castOther.getQuestionInTest())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCourseContentId();
		result = 37 * result + (getCourseId() == null ? 0 : this.getCourseId().hashCode());
		result = 37 * result + this.getQuestionId();
		result = 37 * result + this.getQuestionTypeId();
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + this.getBloomLevelId();
		result = 37 * result + (getQuestionDesc() == null ? 0 : this.getQuestionDesc().hashCode());
		result = 37 * result + (getQuestionInTest() == null ? 0 : this.getQuestionInTest().hashCode());
		return result;
	}

}
